name: CI - Test & Docker Build

on:
  push:
    branches: [ "**" ] # ⬅️ S’exécute à chaque commit, sur toute branche
  pull_request:
    branches: [ "**" ] # ⬅️ S’exécute à chaque commit, sur toutes PR
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run Docker info
        run: docker info

      - name: Run tests with Maven
        run: mvn clean verify -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set Docker tag (commit SHA)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/tempo-rise-api:latest \
                       -t ghcr.io/${{ secrets.GHCR_USERNAME }}/tempo-rise-api:${{ steps.vars.outputs.TAG }} .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/tempo-rise-api:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/tempo-rise-api:${{ steps.vars.outputs.TAG }}