databaseChangeLog:
  - changeSet:
      id: 1
      author: postgres
      changes:
        - sqlFile:
            path: classpath:/db/changelog/2.1.0/scripts/schema.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true



