global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-temporise:8080','host.docker.internal:8080']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: application
        replacement: app-temporise
        regex: 'app-temporise:.*'
      - source_labels: [ __address__ ]
        target_label: application
        replacement: localhost
        regex: 'host.docker.internal:.*'

